// src/components/App.tsx
import { createSignal, Show } from 'solid-js';
import Chooser from './Chooser';
import Editor from './Editor';

function App() {
  const [currentFile, setCurrentFile] = createSignal<string | null>(null);

  return (
    <Show
      when={currentFile()}
      fallback={<Chooser file={currentFile} setFile={setCurrentFile} />}
    >
      <button onclick={() => setCurrentFile(null)}>Back</button>
      <Editor file={currentFile()!} />
    </Show>
  );
}

export default App;

// src/components/App.svelte
<script lang="ts">
  import Chooser from "./Chooser.svelte";
  import Editor from "./Editor.svelte";

  let currentFile: string | null = $state(null);
</script>

{#if currentFile === null}
    <Chooser bind:file={currentFile}/>
{:else}
    <button onclick={() => currentFile = null}>Back</button>
    <Editor file={currentFile}/>
{/if}
